services:
  postgres:
    image: postgres:latest
    volumes:
      - /home/tarv/volumes/codecake/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: codecake
      POSTGRES_PASSWORD: codecake
    ports:
      - "127.0.0.1:5433:5432"